spring:
  application:
    name: hello-dubbo-consumer
  main:
    allow-bean-definition-overriding: true # 不设置会与Spring Boot冲突
dubbo:
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://192.168.179.143:2181,192.168.179.143:2182,192.168.179.143:2183 #注册中心地址
    file: dubbo-registry/dubbo-registry.properties
demo:
  service:
    version: 1.0.0
server:
  port: 8888
